// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-IIUaOzzQfB3QkkMLIf9iQUxf_gMKzec',
    appId: '1:254298723388:web:a2ac4755b8f06bb74c1f39',
    messagingSenderId: '254298723388',
    projectId: 'detection-of-wrongway-vehicles',
    authDomain: 'detection-of-wrongway-vehicles.firebaseapp.com',
    storageBucket: 'detection-of-wrongway-vehicles.firebasestorage.app',
    measurementId: 'G-EEZWK0W9P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUvJ-IOChUrJJkjds5ogVYV95Isvy4rCg',
    appId: '1:254298723388:android:de1de61debb68ab44c1f39',
    messagingSenderId: '254298723388',
    projectId: 'detection-of-wrongway-vehicles',
    storageBucket: 'detection-of-wrongway-vehicles.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr33Q9nAR2Gv2GvaSqxLjICqEJpICtyus',
    appId: '1:254298723388:ios:e4df5bd244b03c304c1f39',
    messagingSenderId: '254298723388',
    projectId: 'detection-of-wrongway-vehicles',
    storageBucket: 'detection-of-wrongway-vehicles.firebasestorage.app',
    iosBundleId: 'com.example.trafficViolationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr33Q9nAR2Gv2GvaSqxLjICqEJpICtyus',
    appId: '1:254298723388:ios:e4df5bd244b03c304c1f39',
    messagingSenderId: '254298723388',
    projectId: 'detection-of-wrongway-vehicles',
    storageBucket: 'detection-of-wrongway-vehicles.firebasestorage.app',
    iosBundleId: 'com.example.trafficViolationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-IIUaOzzQfB3QkkMLIf9iQUxf_gMKzec',
    appId: '1:254298723388:web:fcd093dfe888d05a4c1f39',
    messagingSenderId: '254298723388',
    projectId: 'detection-of-wrongway-vehicles',
    authDomain: 'detection-of-wrongway-vehicles.firebaseapp.com',
    storageBucket: 'detection-of-wrongway-vehicles.firebasestorage.app',
    measurementId: 'G-Z91VP5ZRG0',
  );
}
